### PR TITLE
Move to GHMQs

### PR DESCRIPTION
**Pull request by jacob-hughes**
This will build and test alloy with our fork of BDWGC on CI.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Provided I've set this up correctly. This should be merge-able now that https://github.com/softdevteam/alloy/pull/108 has landed.

**Comment by jacob-hughes** [comment]
I've pushed the fix for this. If you're happy, I can squash

**Comment by vext01** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Comment by jacob-hughes** [comment]
Oops. Fixed here 7d59b341b6a750aa59a8617942e7456a6976d9c0

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
